apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: myvpc1

spec:
        accessModes:
                - ReadWriteOnce
        resources:
                requests:
                        storage: 20Gi
