apiVersion: v1
kind: Pod
metadata:
        name: mypvcpod1

spec:
        containers:
                - name: "mycont1"
                  image: "cankush625/webpage"
                  volumeMounts:
                          - name: web-vol1
                            mountPath: /var/www/html
        volumes:
                - name: web-vol1
                  persistentVolumeClaim:
                          claimName: myvpc1
