apiVersion: v1
kind: ReplicationController

metadata:
  name: "rcweb1"

spec:
  replicas: 1
  selector:
    dc: "US"

  template:
    metadata:
      name: "mypod11"
      labels:
        env: "dev"
        dc: "US"

    spec:
      containers:
      - name: "mycon1"
        image: "cankush625/website"