apiVersion: v1
kind: Service
metadata:
        name: service1
spec:
        selector:
                dc: IN
        type: NodePort
        ports:
                - port: 8080
                  targetPort: 80
                  nodePort: 31000
