apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlpvc1
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "rsdb1"
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      name: "mydb11"
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - name: "mydbcon1"
        image: "mysql:5.6"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mydbsecret1
              key: rootpass
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: db-vol1
            mountPath: /var/lib/mysql
      volumes:
        - name: db-vol1
          persistentVolumeClaim:
            claimName: mysqlpvc1