apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mywppvc1
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: "rsword1"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend

  template:
    metadata:
      name: "mywordpress11"
      labels:
        app: wordpress
        tier: frontend

    spec:
      containers:
      - name: "mywordcon1"
        image: "wordpress:4.8-apache"
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mydbsecret1
              key: rootpass
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
          - name: wp-vol1
            mountPath: /var/www/html
      volumes:
        - name: wp-vol1
          persistentVolumeClaim:
            claimName: mywppvc1